---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- My links:
    - PhlegmaTREEc:
        - abbr: ptc
          href: https://phlegmatreec.com/
    - My Github:
        - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/github.webp
          href: https://github.com/PhlegmaTREEc/

- Links:
    - Homepage:
        - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/homepage.webp
          href: https://gethomepage.dev/

- Favourites:
    - YouTube:
        - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/youtube.webp
          href: https://youtube.com/
    - Aktulane.cz:
        - icon: /icons/640px-aktualne.webp
          href: https://aktualne.cz/
    - Moviezone:
        - abbr: MZ
          href: https://moviezone.cz/
    - Alza.cz:
        - icon: /icons/alza-1080x1200.webp
          href: https://alza.cz/
