services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /home:/srv
      - /home/ptclab/docker/file-browser/filebrowser.db:/database/filebrowser.db
      - /home/ptclab/docker/file-browser/settings.json:/config/settings.json
    restart: always
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 8095:80
