services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      CF_API_TOKEN: /run/secrets/cf_api_token # note using _FILE for docker secrets
      # CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN} # if using .env
    secrets:
      - cf_api_token
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

secrets:
      cf_api_token:
        file: ./cf_api_token.txt

networks:
  proxy:
    external: true

volumes:
  caddy_data:
  caddy_config:
