services:
  foundryvtt:
    hostname: https://foundrytable.local/
    container_name: foundryvtt
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: foundryvtt:12
    restart: unless-stopped
    volumes:
      - /home/ptclab/docker/compose/foundry/foundryvtt:/home/foundry/fvttapp
      - /home/ptclab/docker/compose/foundry/foundrydata:/home/foundry/fvttdata
    ports:
      - 30000:30000
