services:
  foundryvtt:
    hostname: https://foundrytable.local/
    container_name: foundryvtt
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: foundryvtt:12
    restart: no
    volumes:
      - /home/ptclab/docker/foundry/fvvtapp/:/home/foundry/fvttapp
      - /home/ptclab/docker/foundry/fvvtdata/:/home/foundry/fvttdata
    ports:
      - 30000:30000
