services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /home/ptclab/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /home/ptclab/docker/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`hp-traffic.local.phlegmatreec.com`)"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
networks:
  proxy:
    external: true
