exec-once=dms run
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --type text --watch cliphist store &
#exec-once=/usr/lib/polkit-kde-authentication-agent-1 >/dev/null 2>&1 &
exec-once=/usr/lib/xdg-desktop-portal &
exec-once=/usr/lib/xdg-desktop-portal-wlr &
exec-once=/usr/lib/xdg-desktop-portal-cosmic &
exec-once=steam -silent
exec-once=flatpak run com.discordapp.Discord
exec-once=solaar --window=hide
exec-once=com.github.wwmm.easyeffects -w
exec-once=qpwgraph -m
