exec-once=noctalia
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --type text --watch cliphist store &
exec-once=/usr/lib/xdg-desktop-portal &
exec-once=/usr/lib/xdg-desktop-portal-wlr &
exec-once=steam -silent
exec-once=flatpak run com.discordapp.Discord
exec-once=solaar --window=hide
exec-once=com.github.wwmm.easyeffects -w
exec-once=qpwgraph -m
